### ISSUE TITLE
Parsing failed with HTAB?

### ISSUE THREAD

**Issue by shurli** [haraka/node-address-rfc2822#41]
Hi,
I'm using the lib with haraka 2.8.23.
Normally we use the headers.get_decoded for further processing.
Now we found some mails where the from headersfield is empty.

Searching the logfiles and the originalmail source we found that maybe the htab is a problem in email parsing.

this is in the mailsource:
![grafik](https://user-images.githubusercontent.com/24767512/65419119-47f23c80-ddfe-11e9-9bcf-29ab00044262.png)

this is the log message:
![grafik](https://user-images.githubusercontent.com/24767512/65419202-72dc9080-ddfe-11e9-941f-1dbc73ea49e0.png)

decoding of base64 and utf8 seems to work, but parsing not.
I think the mail source is allowed by rfc, as CFWS.

**Comment by msimerson** [comment]
@shurli, did haraka/Haraka#2705 fix this?

**Comment by msimerson** [comment]
closing, due to non-response.
