### ISSUE TITLE
Text between square brackets generates a "No Results" error

### ISSUE THREAD

**Issue by JeremyPouyet** [haraka/node-address-rfc2822#59]
Some addresses I met contain text between brackets and this module generates an error. A simple example:

```javascript
> const addrparser = require('address-rfc2822');
> const addresses = addrparser.parse("Matt Sergeant [hello] <helpme+npm@gmail.com>");
Uncaught Error: No results
    at Object.parse (/home/project/node_modules/address-rfc2822/index.js:32:22)
```
In section [3.2.1 of the RFC2822](https://datatracker.ietf.org/doc/html/rfc2822#section-3.2.1), these brackets are described with `No special semantics are attached to these tokens. They are simply single characters.`
I don't know how the text between brackets should be handled but an error seems inappropriate.

**Comment by msimerson** [comment]
This library name wasn't future-proof, and as the README says, it is now compatible with RFC 5322. Our implementation is now based on [email-addresses](https://github.com/jackbearheart/email-addresses/issues/52) and there's an open issue there regarding brackets. The gist is, they're only allowed when the display name is quoted.
