### ISSUE TITLE
Bug when parsing a string with quotations

### ISSUE THREAD

**Issue by xinbenlv** [haraka/node-address-rfc2822#71]
### Describe the bug

It can't hanlde apostrophe properly

Run this javascript

```js
const addrparser = require('address-rfc2822');
const parsedEmail = addrparser.parse("'foo@bar.com'"); // please note there is a apostrophe (') before and after foo@bar.com
console.log('parsedEmail: ', parsedEmail);
```

It can't hanlde apostrophe properly

### Expected behavior

- Option 1: Fail to parse
- Option 2: Parse as foo@bar.com without the apostrophe

### Observed behavior

It outputs a parsed email address with apostrophe

```
parsedEmail:  [ Address { phrase: '', address: "'foo@bar.com'", comment: '' } ]
```

### Steps To Reproduce

Version: 
```yarn.lock
address-rfc2822@^2.1.0:
  version "2.1.0"
  resolved "https://registry.npmjs.org/address-rfc2822/-/address-rfc2822-2.1.0.tgz"
  integrity sha512-TwoTmJcYzS+CLw/h+AO3zOzRFGSMNowmp/tlOXcYPygkr2vMAWLs0pDajJiJK/dtVPpFx1utw/CzzLfmmtkagw==
  dependencies:
    email-addresses "^4.0.0"
```

### System Info

Please report your OS, Node version, and Haraka version by running this shell script on your Haraka server and replacing this section with the output.

Haraka | bash: haraka: command not found
 --- | :---
Node | v18.20.3
OS | Linux moon-m-zzn-im 6.1.0-21-cloud-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03) x86_64 GNU/Linux
openssl | OpenSSL 3.0.11 19 Sep 2023 (Library: OpenSSL 3.0.11 19 Sep 2023)

**Comment by msimerson** [comment]
Please read RFC [2822](https://www.rfc-editor.org/rfc/rfc2822) and RFC [5322](https://www.rfc-editor.org/rfc/rfc5322) and their successors and point out exactly where we are handling the address incorrectly.

**Comment by xinbenlv** [comment]
@msimerson thanks for pointing it out. What's your suggestion? Shall there be another `node-address-rfc5322` instead or do you think it makes sense to continue to update this repository here?

**Comment by msimerson** [comment]
I suspect the only bug here is your expectations. For further reading, see the RFCs and [https://github.com/jackbearheart/email-addresses/issues/53](https://github.com/jackbearheart/email-addresses/issues/53)
