### ISSUE TITLE
Better handling non-latin names

### ISSUE THREAD

**Issue by vladgolubev** [haraka/node-address-rfc2822#8]
Hey @haraka

Thanks for the module!

By the way I found a little issue with non-latin names.

I suppose the culprit is here - https://github.com/haraka/node-address-rfc2822/blob/master/index.js#L258

When it tries to parse non-latin names it makes them all lowercase, because `\b` doesn't match begging non-ASCII names.

F.e. try to parse `"Имя Фамилия" <name@gmail.com>`

Would you like to accept a PR? I could make it immediately, but not sure if project is still alive so it will be merged at sometime.

**Comment by Dexus** [comment]
Hello Vlad,

sure any PR is welcome. We use this plugin in haraka, so its stile active.

Regards,
Josef

**Comment by msimerson** [comment]
Hi again @vladgolubev . Thanks for updating. I looked into `is-upper-case`, which is a thin wrapper around `upper-case`, which in turn is still using a regexp, but is doing so using some unicode ranges. While that's a reasonable thing to do, I think it's less than ideal. 

Using native `toLowerCase()` and `toUpperCase()` has a couple advantages:

1. it's faster
2. doesn't introduce a dependency
3. the native case functions already have unicode support
4. I'd expect the native functions to "get it right" on more languages than the unicode character ranges
5. the code inside that function uses toLowerCase and toUpperCase, so it's unlikely there will ever be mismatches between what is detected and what is transformed.

Your thoughts?
